variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - test
  - build

test:
  image: python:3.10.4-slim-bullseye
  before_script:
    - apt-get update && apt-get install make
    - pip install nose2
  stage: test
  script:
    - pip install -r requirements.txt
    - make test

build:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info
  stage: build
  script:
    - docker build -f docker/dockerfile --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
