FROM python:3.7.7-slim-buster as generate_data

RUN mkdir -p /srv
COPY requirements.txt /srv/
RUN mkdir -p /srv/indexer
COPY indexer/*.py /srv/indexer/
RUN mkdir -p /srv/extractor
COPY extractor/*.py /srv/extractor/
RUN mkdir -p /srv/data/logs

RUN mkdir -p /srv/catalan-dict-tools/
COPY catalan-dict-tools/ /srv/catalan-dict-tools/

# Generate data set
WORKDIR /srv
RUN pip install -r requirements.txt
RUN ./extractor/extract.py
RUN ./indexer/index_creation.py

FROM python:3.7.7-slim-buster
RUN apt-get update -y && apt-get upgrade -y

COPY requirements.txt /srv/
RUN pip install -r /srv/requirements.txt
COPY docker/entrypoint.sh /srv/
COPY web/*.py /srv/web/
COPY web/models/*.py /srv/web/models/


COPY --from=generate_data /srv/data /srv/data
RUN pip install gunicorn

ENTRYPOINT srv/entrypoint.sh


