FROM debian:bookworm-slim as generate_data

RUN apt-get update && apt-get install bzip2 make
COPY --from=ghcr.io/astral-sh/uv:0.9.13 /uv /uvx /bin/
RUN mkdir -p /srv
COPY pyproject.toml uv.lock Makefile /srv/
RUN mkdir -p /srv/indexer
COPY indexer/*.py /srv/indexer/
RUN mkdir -p /srv/extractor
COPY extractor/*.py /srv/extractor/
COPY extractor/replace_diacritics_iec.txt /srv/extractor/
COPY extractor/reflexius.txt /srv/extractor/
COPY extractor/notes.json /srv/extractor/
RUN mkdir -p /srv/data/logs
COPY definitions/*.py /srv/definitions/
COPY definitions/*.bz2 /srv/definitions/

RUN mkdir -p /srv/catalan-dict-tools/
COPY catalan-dict-tools/ /srv/catalan-dict-tools/

# Generate data set
WORKDIR /srv
COPY .python-version /srv/
RUN uv python install $(cat .python-version)
RUN uv sync
RUN make generate-data

FROM debian:bookworm-slim
RUN apt-get update -y && apt-get upgrade -y
COPY --from=ghcr.io/astral-sh/uv:0.9.13 /uv /uvx /bin/

COPY pyproject.toml uv.lock /srv/
COPY .python-version /srv/
WORKDIR /srv
RUN uv python install $(cat .python-version)
RUN uv sync
COPY docker/entrypoint.sh /srv/
COPY definitions/*.py /srv/indexer/
COPY indexer/*.py /srv/indexer/
COPY extractor/*.py /srv/extractor/
COPY web/*.py /srv/web/
COPY web/models/*.py /srv/web/models/


COPY --from=generate_data /srv/data /srv/data

ENTRYPOINT /srv/entrypoint.sh


