FROM python:3.6.1
#RUN apt-get update && apt-get install python3-dev libhunspell-dev gettext -y
RUN git clone --depth=1 https://github.com/Softcatala/conjugador conjugador

WORKDIR conjugador

#Web server
RUN pip install gunicorn

EXPOSE 8080 8000

WORKDIR web

#What get's executed on Run
ENTRYPOINT gunicorn web_search:app -b 0.0.0.0:8000


